-- MySQL Script generated by MySQL Workbench
-- Fri Sep 17 18:50:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DataBaseTienda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DataBaseTienda` ;

-- -----------------------------------------------------
-- Schema DataBaseTienda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DataBaseTienda` DEFAULT CHARACTER SET utf8 ;
USE `DataBaseTienda` ;

-- -----------------------------------------------------
-- Table `DataBaseTienda`.`cllientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataBaseTienda`.`cllientes` (
  `cedula_cliente` BIGINT(20) NOT NULL,
  `direccion_cliente` VARCHAR(255) NULL,
  `email_cliente` VARCHAR(255) NULL,
  `nombre_cliente` VARCHAR(255) NULL,
  `telefono_cliente` VARCHAR(255) NULL,
  PRIMARY KEY (`cedula_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DataBaseTienda`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataBaseTienda`.`usuarios` (
  `cedula_usuario` BIGINT(20) NOT NULL,
  `email_usuario` VARCHAR(255) NULL,
  `nombre_usuario` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `usuario` VARCHAR(255) NULL,
  PRIMARY KEY (`cedula_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DataBaseTienda`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataBaseTienda`.`ventas` (
  `codigo_venta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cedula_cliente` BIGINT(20) NULL,
  `cedula_usuario` BIGINT(20) NULL,
  `iva_venta` DOUBLE NOT NULL,
  `total_venta` DOUBLE NOT NULL,
  `valor_venta` DOUBLE NOT NULL,
  `cllientes_cedula_cliente` BIGINT(20) NOT NULL,
  `usuarios_cedula_usuario` BIGINT(20) NOT NULL,
  PRIMARY KEY (`codigo_venta`),
  CONSTRAINT `fk_ventas_cllientes`
    FOREIGN KEY (`cllientes_cedula_cliente`)
    REFERENCES `DataBaseTienda`.`cllientes` (`cedula_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`usuarios_cedula_usuario`)
    REFERENCES `DataBaseTienda`.`usuarios` (`cedula_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ventas_cllientes_idx` ON `DataBaseTienda`.`ventas` (`cllientes_cedula_cliente` ASC) VISIBLE;

CREATE INDEX `fk_ventas_usuarios1_idx` ON `DataBaseTienda`.`ventas` (`usuarios_cedula_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `DataBaseTienda`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataBaseTienda`.`proveedores` (
  `nitproveedor` BIGINT(20) NOT NULL,
  `ciudad_proveedor` VARCHAR(255) NULL,
  `direccion_proveedor` VARCHAR(255) NULL,
  `nombre_proveedor` VARCHAR(255) NULL,
  PRIMARY KEY (`nitproveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DataBaseTienda`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataBaseTienda`.`productos` (
  `codigo_producto` BIGINT(20) NOT NULL,
  `iva_compra` DOUBLE NOT NULL,
  `nit_proveedor` BIGINT(20) NULL,
  `nombre_producto` VARCHAR(255) NULL,
  `precio_compra` DOUBLE NOT NULL,
  `precio_venta` DOUBLE NOT NULL,
  `proveedores_nitproveedor` BIGINT(20) NOT NULL,
  PRIMARY KEY (`codigo_producto`),
  CONSTRAINT `fk_productos_proveedores1`
    FOREIGN KEY (`proveedores_nitproveedor`)
    REFERENCES `DataBaseTienda`.`proveedores` (`nitproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_productos_proveedores1_idx` ON `DataBaseTienda`.`productos` (`proveedores_nitproveedor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `DataBaseTienda`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DataBaseTienda`.`detalle_ventas` (
  `cod_detalle_venta` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cant_producto` INT(20) NOT NULL,
  `codigo_prod` BIGINT(20) NULL,
  `cod_venta` BIGINT(20) NULL,
  `valor_total` DOUBLE NOT NULL,
  `valor_venta` DOUBLE NOT NULL,
  `valoriva` DOUBLE NOT NULL,
  `ventas_codigo_venta` BIGINT(20) NOT NULL,
  `productos_codigo_producto` BIGINT(20) NOT NULL,
  PRIMARY KEY (`cod_detalle_venta`),
  CONSTRAINT `fk_detalle_ventas_ventas1`
    FOREIGN KEY (`ventas_codigo_venta`)
    REFERENCES `DataBaseTienda`.`ventas` (`codigo_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ventas_productos1`
    FOREIGN KEY (`productos_codigo_producto`)
    REFERENCES `DataBaseTienda`.`productos` (`codigo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_detalle_ventas_ventas1_idx` ON `DataBaseTienda`.`detalle_ventas` (`ventas_codigo_venta` ASC) VISIBLE;

CREATE INDEX `fk_detalle_ventas_productos1_idx` ON `DataBaseTienda`.`detalle_ventas` (`productos_codigo_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
